# fly.toml app configuration file generated for backend-young-brook-474 on 2024-10-09T15:07:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-young-brook-474'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
