name: Run python app

on:
  schedule:
    # This runs every 3 hours
#    - cron: '0 */3 * * *'

      # This runs every 100 minutes, from 9am to 2am GMT+8
    - cron: '*/100 1-17 * * *'

  workflow_dispatch:
    # Allows workflow to run manually for testing

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
  SHEETS_JSON: ${{ secrets.SHEETS_JSON }}
  GMAIL_JSON: ${{ secrets.GMAIL_JSON }}
  VERIFICATION_EMAIL: ${{ secrets.VERIFICATION_EMAIL }}

jobs:
  cron_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
