name: Run python app

on:
  schedule:
    # This runs every 4 hours
    - cron: '0 */3 * * *'

  workflow_dispatch:
    # Allows workflow to run manually for testing

jobs:
  cron_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
